### ISSUE TITLE
"execute cannot be used while an asynchronous query is underway", when use it in gevent greenlets

### ISSUE THREAD

**Issue by viatoriche** [iiilx/django-psycopg2-pool#12]
How can I fix it?

**Comment by viatoriche** [comment]
```
Django 1.6.5
>>> from django.db import connection
>>> cursor = connection.cursor()
>>> import gevent
>>> gevent.joinall([gevent.spawn(cursor.execute, 'SELECT pg_sleep(1)'), gevent.spawn(cursor.execute, 'SELECT pg_sleep(1)'), gevent.spawn(cursor.execute, 'SELECT pg_sleep(1)'), gevent.spawn(cursor.execute, 'SELECT pg_sleep(1)')])
Traceback (most recent call last):
  File "/home/viatoriche/Dropbox/coding/envs/onetrak/local/lib/python2.7/site-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/viatoriche/Dropbox/coding/envs/onetrak/local/lib/python2.7/site-packages/django/db/backends/util.py", line 69, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/viatoriche/Dropbox/coding/envs/onetrak/local/lib/python2.7/site-packages/django/db/backends/util.py", line 51, in execute
    return self.cursor.execute(sql)
  File "/home/viatoriche/Dropbox/coding/envs/onetrak/local/lib/python2.7/site-packages/django_psycopg2_pool-0.1.1-py2.7.egg/django_psycopg2_pool/gevent/base.py", line 57, in execute
    return self.cursor.execute(query, args)
DatabaseError: execute cannot be used while an asynchronous query is underway
<Greenlet at 0x7fd22eb9c5f0: <bound method CursorDebugWrapper.execute of <django.db.backends.util.CursorDebugWrapper object at 0x7fd22eba3e90>>('SELECT pg_sleep(1)')> failed with DatabaseError

Traceback (most recent call last):
  File "/home/viatoriche/Dropbox/coding/envs/onetrak/local/lib/python2.7/site-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/viatoriche/Dropbox/coding/envs/onetrak/local/lib/python2.7/site-packages/django/db/backends/util.py", line 69, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/viatoriche/Dropbox/coding/envs/onetrak/local/lib/python2.7/site-packages/django/db/backends/util.py", line 51, in execute
    return self.cursor.execute(sql)
  File "/home/viatoriche/Dropbox/coding/envs/onetrak/local/lib/python2.7/site-packages/django_psycopg2_pool-0.1.1-py2.7.egg/django_psycopg2_pool/gevent/base.py", line 57, in execute
    return self.cursor.execute(query, args)
DatabaseError: execute cannot be used while an asynchronous query is underway
<Greenlet at 0x7fd22eb9c050: <bound method CursorDebugWrapper.execute of <django.db.backends.util.CursorDebugWrapper object at 0x7fd22eba3e90>>('SELECT pg_sleep(1)')> failed with DatabaseError

Traceback (most recent call last):
  File "/home/viatoriche/Dropbox/coding/envs/onetrak/local/lib/python2.7/site-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/viatoriche/Dropbox/coding/envs/onetrak/local/lib/python2.7/site-packages/django/db/backends/util.py", line 69, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/viatoriche/Dropbox/coding/envs/onetrak/local/lib/python2.7/site-packages/django/db/backends/util.py", line 51, in execute
    return self.cursor.execute(sql)
  File "/home/viatoriche/Dropbox/coding/envs/onetrak/local/lib/python2.7/site-packages/django_psycopg2_pool-0.1.1-py2.7.egg/django_psycopg2_pool/gevent/base.py", line 57, in execute
    return self.cursor.execute(query, args)
DatabaseError: execute cannot be used while an asynchronous query is underway
<Greenlet at 0x7fd22eb9c4b0: <bound method CursorDebugWrapper.execute of <django.db.backends.util.CursorDebugWrapper object at 0x7fd22eba3e90>>('SELECT pg_sleep(1)')> failed with DatabaseError
```

**Comment by viatoriche** [comment]
I must use DatabaseConnectionPool.execute instead of cursor.execute for all execute, but I don't know how do it in django ORM
